package com.example.quanlybanquanao.enums;

public enum AdminAction {
    CREATE_ADMIN_USER,
    UPDATE_ADMIN_USER,
    DELETE_ADMIN_USER,
    UPDATE_ADMIN_PASSWORD,
    CHANGE_PASSWORD,
    CREATE_ADMIN_USER_ROLE,
    UPDATE_ADMIN_USER_ROLE,
    DELETE_ADMIN_USER_ROLE,
    CREATE_PRODUCT,
    SOFT_DELETE_PRODUCT,
    UPDATE_PRODUCT,
    GET_PRODUCT_DETAIL,
}
